initial french translation
arc42/arc42-template pull request #190
Opened 2023-06-05 13:20 UTC by dlucasd

Hi,

Here's the french translation of this great template.
Thanks!

2023-06-05 14:05 UTC, gernotstarke commented
Hi there,
thanx for your awesome contribution...

We're briefly reviewing it (I just found a French-speaking colleague)...

It would be good if you could reveal your name, so we can add a "thank you" on the landing page,
when we announce the new version!!
It would be perfectly ok if you prefer not to be named, then it will be an anonymous contribution...

regards from Cologne,
Gernot (co-founder and core maintainer of arc42)

2023-06-05 14:21 UTC, gernotstarke commented
thanx @martinweck for providing review comments

2023-06-05 18:46 UTC, dlucasd commented
My name is Damien Lucas!

Regards from Bordeaux
Damien

2023-06-06 09:20 UTC, martinweck requested changes
Hi Damien,
Thank you so much for your contribution. I am not a native speaker. Hence, if you go through my comments and you feel that they are just wrong, because of my lack of language skills, then just close the comment without action. We have asked also a French-speaking colleague to have a look as well, but for me, it looks all great, only maybe some minor remarks.

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/01_introduction_and_goals.adoc
> +Ces éléments sont les suivants
```
Il s'agit notamment

- des objectifs commerciaux sous-jacents, 
...
```
I was wondering if it is not better to avoid the usage of the word "élements" which could have certain meanings for certain people (if I am a nitpicker, you may ignore this).

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/01_introduction_and_goals.adoc
> +=== Objectifs Qualité
Objectifs de Qualité

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/01_introduction_and_goals.adoc
> +Lien vers (en espérant qu'ils existent) les documents relatifs aux exigences (avec le numéro de version et des informations sur l'endroit où les trouver).
I think already in the English version, links should be in plural, since there are multiple documents, hence:
Liens (en espérant qu'ils existent) vers des documents relatifs aux exigences.

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/01_introduction_and_goals.adoc
> +Lien vers (en espérant qu'ils existent) les documents relatifs aux exigences (avec le numéro de version et des informations sur l'endroit où les trouver).
I am not sure with my French: I was wondering regarding the expression "des documents relatifs aux exigences" vs. "des documents d'exigences". Is it not that "des documents d'exigences" are documents that state requirements explicitly (that is what Gernot means, I have just asked him)? In contrast "des documents relatifs aux exigencies" are documents that relate to requirements which is more indirect?

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/04_solution_strategy.adoc
> +* décisions technologiques
décisions -> les décisions

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/04_solution_strategy.adoc
> +* décisions relatives à la décomposition du système au niveau le plus élevé, par exemple l'utilisation d'un modèle architectural ou d'un modèle de conception
décisions -> les décisions

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/04_solution_strategy.adoc
> +* décisions sur la manière d'atteindre les principaux objectifs de qualité
décisions -> les décisions

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/04_solution_strategy.adoc
> +Se référer aux détails des sections suivantes.
To be honest, I don't understand what is meant by "Refer to details in the following sections". Since it is an issue of the original text, I have asked Gernot, who will adapt it. You may take his adapted text or just omit it. However, I would add information on the table with the quality goals and how they can be reached. Hence:
```
Pour documenter la manière d'atteindre les principaux objectifs de qualité, vous pouvez utiliser le tableau suivant :

[options="header",cols="1,1,1,1"]
|===
|Objectif de qualité|Scénario|Approche de la solution|Lien vers les détails
| _<Objectif-Q1>_ | _<Scénario-1>_ | _<Solution-1>_ | _<Lien-1>_
| _<Objectif-Q2>_ | _<Scénario-2>_ | _<Solution-2>_ | _<Lien-2>_
|===
```

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/05_building_block_view.adoc
> +*Niveau 1* est la description en boîte blanche du système global ainsi que la description en boîte noire de toutes les briques qu'il contient.
Actually, "Scope & Context" within the picture is what we have documented in "3 - Context and Scope", so we could call it Level 0 or "Niveau Contexte et Périmètre". So the English text does not fit the picture :(. Hence my suggestion:
*Niveau Contexte et Périmètre (Niveau 0)* a été décrit dans la section https://docs.arc42.org/section-3/[Context and Scope]. C'est pourquoi il n'est pas décrit ici, mais vous pouvez éventuellement insérer un lien vers https://docs.arc42.org/section-3/[Context and Scope].
*Niveau 1* est la description...
*Niveau 2* est un zoom...de leurs briques internes, et ainsi de suite pour les autres niveaux.

=> I would skip Niveau 3 as it is not in the picture

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/05_building_block_view.adoc
> +=== Système global Boîte blanche
`=== Système global Boîte blanche` -> `=== Niveau 1 : Système global Boîte blanche`

=> I am aware that this is also different from the English version, but this small change would ease the reader's orientation.

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/05_building_block_view.adoc
> +==== Boîte blanche _<brique m>_
`_<brique n>_` ?

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/05_building_block_view.adoc
> +****
I would add the following sentence and then I would even skip the whole section "Niveau 3" to be consistent with the picture. Since this is quite a change in comparison to the English version, you may decide whether you do that change or if you just close this review comment.

> Si vous avez besoin de niveaux plus détaillés de votre architecture, c'est-à-dire des niveaux 3, 4 et ainsi de suite, veuillez copier cette partie d'arc42 pour les niveaux supplémentaires.

2023-06-06 09:20 UTC, martinweck commented on FR/asciidoc/src/05_building_block_view.adoc
> +*Niveau 1* est la description en boîte blanche du système global ainsi que la description en boîte noire de toutes les briques qu'il contient.
I have informed Gernot about it who may adapt it as well

2023-06-06 09:59 UTC, martinweck commented on FR/asciidoc/src/12_glossary.adoc
> +
Maybe, you could add a table here. IMHO it makes it easier for the reader to understand how a glossary could look like, something like:

```
[options="header",cols="1,1"]
|===
|Terme|Définition
| _<Term-1>_ | _<Définition-1>_
| _<Term-2>_ | _<Définition-2>_ | _<Solution-2>_ | _<Lien-2>_
|===
```

2023-06-06 11:17 UTC, martinweck approved these changes
since there are no important things, as with Gernot discussed it's approved

2023-06-06 11:17 UTC, martinweck approved these changes
since there are no important things, as with Gernot discussed it's approved

2023-06-06 11:17 UTC, martinweck approved these changes

2023-06-06 12:47 UTC, gernotstarke approved these changes
Damien, if you like the comments from @martinweck , please feel free to include them.
Otherwise, I gladly accept your PR.

Due to the technical setup of arc42, it might take a few days to have the download available on the official website (we have another person review changes to the downloads... )

Thanx again, merci beaucoup!

2023-06-06 13:41 UTC, dlucasd commented on FR/asciidoc/src/01_introduction_and_goals.adoc
> +Lien vers (en espérant qu'ils existent) les documents relatifs aux exigences (avec le numéro de version et des informations sur l'endroit où les trouver).
Sure, "des documents relatifs aux exigences" is more indirect. But "des documents d'exigences" is not quite good.
We debated with my colleagues and "des documents décrivant les exigences" is more accurate

2023-06-06 13:41 UTC, dlucasd commented on FR/asciidoc/src/05_building_block_view.adoc
> +****
Sure, the third part is redundant. I change that.

2023-06-06 13:48 UTC, dlucasd commented
Hi @gernotstarke , @martinweck ,

I've made the corrections in response to the @martinweck's code review.

2023-06-07 06:59 UTC, martinweck commented
Hi @dlucasd,
Thanks a lot for those updates! For me, it is perfect now and can be merged.

2023-06-07 07:01 UTC, martinweck commented
@gernotstarke github displays "1 workflow awaiting approval", maybe you can look into it and then you can merge it (I think I don't have the rights)

2023-06-07 08:22 UTC, gernotstarke approved these changes
thanx everybody

2023-06-07 08:22 UTC, merged

2023-06-12 06:49 UTC, gernotstarke commented
@dlucasd I gave you triage-rights on the repo, so I can assign you as reviewer to Pull-Requests...

Reason: We received a few comments to your french translation - and my French is too bad to comment on those :-)

Would be great if you could accept the triage invite, so I can assign you to this new PR...